### ISSUE TITLE
[BUG] Sentences for recording have "?" in place of expected special Latvian characters

### ISSUE THREAD

**Issue by raivisdejus** [common-voice/common-voice#4138] opened 2023-08-03 18:11 UTC
**Describe the bug**
Text encoding in the database seems corrupt. Sentences affected seem to be added from the Common Voice UI, most likely they looked fine when they were validated, but on the recording screen they look corrupt, Latvian symbols like `č`, `ā`, `ē` and similar are displayed as `?`

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/lv/speak
2. Check in the developer tools sentences that were loaded for recording. 

Some of the sentences will have `?` in the middle of the sentence where special Latvian letters should be. An example

```
id: "02ea84f2c2f9944d19bfb369b70f54b4d235c66ffd67c2413978001095a6a832"
text received from the server: "Ku?ier, tu lab?k proti, sit tu!"
text most likely in the sentence: "Kučier, tu labāk proti, sit tu!"
``` 
Another

```
id: "3176d6952f89b1ac08acfe756a0f3722979522c12406d72983e2583b2d947129"
text received from the server: "Beidziet flirt?t ar prec?tiem cilv?kiem!"
text most likely in the sentence: "Beidziet flirtēt ar precētiem cilvēkiem!"
``` 

**Expected behavior**
Sentences with proper characters are loaded for recording and there are no `?` in the middle of the sentences

**Comment by HarikalarKutusu** [comment] 2023-08-03 18:42
Same for special Turkish characters:

![image](https://github.com/common-voice/common-voice/assets/8849617/d6c8fe37-c1b0-4e9b-8248-a0f5b4c97150)

But I'm not sure if these are from old sentences or from recently entered ones through the new interface.

**Comment by moz-rotimib** [comment] 2023-08-03 19:22
Hello @raivisdejus thanks for reporting this.

This issue was fixed in #4111 but unfortunately, sentences created before this fix was released will still have this weird formatting. Any sentences added after this fix should have the proper encoding and should display correctly. 

If you are still encountering this with a sentence added after this fix was released feel free to respond in the thread

**Comment by ftyers** [comment] 2023-08-03 19:28
@moz-rotimib is it possible to remove all sentences that were badly encoded? Because these sentences aren't really pronounceable and will harm STT models.

**Comment by HarikalarKutusu** [comment] 2023-08-03 20:02
I second @ftyers.

> weird formatting

Are they just weirdly displayed or are they malformed in the database? If malformed, is it a 1-to-1 mapped unicode character which cannot be displayed or are they replaced by question marks?

If these are not correctable, they should be removed for sure.

I (in-)validated many sentences (>1000) from imports in the past few days and I'm afraid they might end like this. I will not use the interface until it is sorted,

Maybe it will be best to make an announcement on this so that people don't get frustrated.

**Comment by raivisdejus** [comment] 2023-08-04 06:13
Agree on removing malformed sentences. Should be possible to find them in the DB and remove them.

**Comment by moz-dfeller** [comment] 2023-08-07 10:13
Actually #4111 and #4113 are about the source field, which had a wrong encoding (standard `latin1`). The sentences themselves should be correctly encoded as they are saved as `utf8mb4` encoded strings. So I assume it's a display error.

**Comment by HarikalarKutusu** [comment] 2023-08-07 11:34
I get reports of those malformed sentences from the community. As they are mostly deductible in Turkish, some people record them as they should be, but some use the "Report" button - which does nothing in terms of the workflow. During validation, the path is again not well defined. Some people use the Report button, and some people down-vote (I tell them to downvote).

In any case, I have no idea how these can be cleaned across all languages if they get into the dataset release.
@moz-dfeller, I think this is an issue of the highest priority in terms of dataset health and validity.

**Comment by moz-dfeller** [comment] 2023-08-07 15:17
These sentences are stored inside the database containing question marks. I tried to reproduce the issue by entering sentences with Latvian special characters via desktop and mobile phone browser and check how they arrive in the database. So far, I can say that they are stored correctly using the interface. The latest submitted sentences don't contain question marks as well.

I first suspected that they might have been an encoding problem during the sentence migration from the old sentence-collector database into the CV database. But I checked a few sentences and they are neither inside the `sentence-collector.txt` in `/data/{locale}` nor inside the the old sentence-collector db dump. Which means that they must have come via interface. But it seems that it doesn't happen all the time which makes it hard to track down.

**Comment by HarikalarKutusu** [comment] 2023-08-07 15:36
I checked the sentence "Zamanın azalıyor", the one I posted above, and it is not under server/data/tr/*.txt either. I cannot check further as we have no access to new text-corpora :( Also, because there are thousands of sentences imported from sentence-collector db dump, I cannot test unless I clean all waiting validations.

The thing is: For Turkish, it only seems to happen to characters that are NOT in Latin-1 (ISO-8859-1) - "ı" is one of them. Which might point to an encoding problem again.

During the rollout of the new interface, before you imported the remaining data from the sentence-collector, I tested it with all special Turkish characters, and it was working OK. So I thought it should be the export/import process... But you say otherwise...

**Comment by moz-dfeller** [comment] 2023-08-07 15:58
I just entered your special characters to test. Here is a screenshot from the production DB entry:
<img width="1863" alt="image" src="https://github.com/common-voice/common-voice/assets/119537889/ca37e64c-8b9e-40ce-9050-046be7504b53">
The characters are stored correctly. So the search continues :(

**Comment by moz-dfeller** [comment] 2023-08-08 13:09
@HarikalarKutusu The encoding of the database field is correct, as you could see from the screenshot, the characters are encoded correctly. The malformed characters also don't seem to come from the sentence-collector migration as I stated earlier as I couldn't find `Zamanın azalıyor` and other sentences that are malformed. I will implement some extra logging when the sentences are written to the DB and check if the the user client and/or the device are the culprit.

**Comment by HarikalarKutusu** [comment] 2023-08-08 15:24
I was referring to this:

> These sentences are stored inside the database containing question marks.

If I understand this correctly the dump might contain `Zaman?n azal?yor`...
Just a hunch :/

**Comment by raivisdejus** [comment] 2023-08-09 18:28
I do not fully follow the thought process here, but my thinking on this would be:

**Are the sentences in the DB with or without the `?` right now?**
If yes, they have `?` in the DB then the data is broken and the next question would be if we have some backup or other way to get the data correct back. If we can think of a way to fix this, let's look for a solution, but if there is no solution then let's first remove or at least hide the sentences with `?` that are in the middle of some word from the UI for now. E.g. by setting `is_used` column for those sentences to `FALSE`.

Proper investigation and fix may take time, so some solution to mitigate the issue would be very welcome.

**Comment by raivisdejus** [comment] 2023-08-09 18:46
BTW, I am seeing sentences that do not have any text or seem truncated. All the marked sentences have some issue 

![attels](https://github.com/common-voice/common-voice/assets/5319134/c1557a04-298f-47b5-9a96-159437e9d62d)

**Comment by moz-dfeller** [comment] 2023-08-10 08:31
Hey @raivisdejus,
to answer your questions:
> Are the sentences in the DB with or without the ? right now?
The sentences are stored with the `?` in the database. Restoring them doesn't seem to be possible since I couldn't find the original sentence in the sentence-collector, e.g. `Urbis sagr?ba mikrofonu, ier?kdamies:` comes from `Latvie?u pasaules dikt?ta teikumi no https://raksti.org/`. So I guess for the time being setting these sentences to `is_used=false` is a good first step. 

Many of the truncated sentences come from the `Pa?atsauce` source. I don't know what that means, maybe you can make sense of it.

**Comment by raivisdejus** [comment] 2023-08-10 09:36
@moz-dfeller Can you please remove / hide all Latvian sentences:
- with source `Pa?atsauce`
- that have `?` in the middle of the word

Removing all sentences with source `Latvie?u pasaules dikt?ta teikumi no https://raksti.org/` can also be an option as they seem to be broken.

**Closed** 2023-08-29 17:00 UTC
Labels: Bug
