### ISSUE TITLE
Marathi Language Localization Request

### ISSUE THREAD

**Issue by Sam5unG** [common-voice/common-voice#3013] opened 2021-02-15 20:08 UTC
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
-Marathi

**Language code**
Please provide the ISO-639-1 code
mr

**Language size**
Number of active speakers of this language in the world
~83 Million

**Plural forms**
How would you translate the following in this language?

0 rocks - ० दगड
1 rock - १ दगड
2 rocks -२ दगड
3 rocks - ३ दगड
4 rocks - ४ दगड
5 rocks - ५ दगड
10 rocks - १० दगड
20 rocks - २० दगड
100 rocks - १०० दगड
1000 rocks - १००० दगड
I see 0 rocks on the ground  - मला जमिनीवर ० खडक दिसत आहेत
I see 1 rock on the ground - मला जमिनीवर १ खडक दिसत आहे
I see 10 rocks on the ground -मला जमिनीवर १० खडक दिसत आहे
I see rocks on the ground - मला जमिनीवर अनेक खडक दिसत आहेत 

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/2NK6PNDEret4722fcUJ06BLHrIU/

**Comment by ftyers** [comment] 2021-02-15 20:20
This is a duplicate of #3004.

**Closed** 2021-03-26 20:08 UTC
