### ISSUE TITLE
LOCALIZATION REQUEST: Add Galician to voice recording on https://commonvoice.mozilla.org/gl

### ISSUE THREAD

**Issue by meixome** [common-voice/common-voice#3020] opened 2021-02-18 23:31 UTC
Use this template to request a new localizable language that is currently not available

Galician is already 100% translated on Pontoon

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. 

Today we are reaching the 5000 sentences, to minimal milestone for open the recording.
We are working very hard in quickly enlarge our corpus and sentence's volume available for voice contributors
We already have script for upload sentences from Wikipedia

**Language name**
What language would you like to add?
Galego (Galician in english)

**Language code**
Please provide the ISO-639-1 code
gl

**Language size**
Number of active speakers of this language in the world

3.350.000 all over the world

**Plural forms**
How would you translate the following in this language?

0 rochas
1 rocha
2 rochas
3 rochas
4 rochas
5 rochas
10 rochas
20 rochas
100 rochas
1000 rochas
Vexo 0 rochas no chan
Vexo 1 rocha no chan
Vexo 10 rochas no chan
Vexo rochas no chan

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

Antón Méixome
https://pontoon.mozilla.org/contributors/SF5qQI-e6BYkOM9oO9CzjqKZVDM/

Please, update data about sentences in corpus also in https://commonvoice.mozilla.org/gl/languages

**Comment by ftyers** [comment] 2021-02-18 23:46
Dear @meixome Galician is already enabled in Pontoon and [localised](https://pontoon.mozilla.org/gl/common-voice/). This is a duplicate of  #3008.

**Comment by meixome** [comment] 2021-02-19 00:44
Yes, I say the same. I Know because I'm the translator ;-)
I want open open https://commonvoice.mozilla.org/gl 
because we already have the 5000 validate sentences in sentence-collector
We need to take benefit of the wave in the galician community about contributions.

**Comment by ftyers** [comment] 2021-02-19 01:45
Ok, in that case, then perhaps change the text and title of the issue? The way is it currently worded, and with the Pontoon-information makes what you are asking for unclear. Here is an [example issue](https://github.com/common-voice/common-voice/issues/2980) about launching a language on the main site.. Note that at the moment there will likely be a delay for a few weeks because of [changes at Common Voice](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526):
>As we go through this transition, Common Voice will remain up and accessible, but there will be a period from mid February to early March, where there will not be immediate support available.

**Comment by meixome** [comment] 2021-02-19 09:42
@ftyers Thanks a lot for your attention
I have submitted another issue and I hope it's correct now
https://github.com/common-voice/common-voice/issues/3022

P.S. We know about delay also

**Comment by ftyers** [comment] 2021-02-19 14:08
@meixome Great! Can you close this issue?

**Closed** 2021-02-19 18:57 UTC
