### ISSUE TITLE
[BUG] "Speak" returns only 1 sentence instead of 5

### ISSUE THREAD

**Issue by gullabi** [common-voice/common-voice#3648] opened 2022-03-31 13:34 UTC
**Describe the bug**
When "[speak](https://commonvoice.mozilla.org/en/speak)" page is clicked in order to start recording, only one sentence is shown to record. All languages are affected. 

**To Reproduce**
1. Go to the main page
2. Click on Speak
3. See only one sentence appearing instead of five
4. After recording see only one sentence before sending it to the server

**Expected behavior**
In speak 5 sentences should appear.

**Screenshots**
English speak page
![en](https://user-images.githubusercontent.com/40303490/161066841-5533f01f-8711-4bb4-a6e3-0700c8c8e203.png)
Azeri send page after single recording
![qulaq](https://user-images.githubusercontent.com/40303490/161066974-1d821953-957a-47ce-837c-00a4de511281.png)
Mobile English speak also allows for a single sentence recording
![photo_2022-03-31_15-25-31](https://user-images.githubusercontent.com/40303490/161067259-66b9fe38-e606-41ed-8d4b-19c92e2d1836.jpg)

**Desktop or Mobile (please complete the following information):**
 - OS: Android, Ubuntu 20
 - Browser Firefox
 - Version 96.0

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
N/A

**Additional context**
N/A

**Comment by robovoice1** [comment] 2022-03-31 15:15
Duplicate of https://github.com/common-voice/common-voice/issues/3647

**Closed** 2022-04-01 08:26 UTC
Labels: Bug
