### ISSUE TITLE
New language: Māori

### ISSUE THREAD

**Issue by OliverDeBrisbane** [common-voice/common-voice#3132] opened 2021-05-23 08:25 UTC
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language**
Māori

**ISO code**
mi

**Language size**
~150,000 fluent in New Zealand, ~15,000 in Australia

**Plural forms**
1 toka (1 rock)
2 toka (2 rocks) OR 2 ngā toka (2 rocks)
See https://www.maoridictionary.co.nz/ for more. 

**Pontoon manager**
I don’t know. You can contact https://www.tetaurawhiri.govt.nz/en/ (Te Taura Whiri i te reo Māori/Māori Language Commission) to help. I don’t use Pontoon, I came here from Mozilla Common Voice. Please consider adding Māori. You could get help from agencies such as the Māori Language Commission, Auckland University, Māori Dictionary and/or the New Zealand Government.

**Comment by MichaelKohler** [comment] 2021-05-23 08:27
I'm closing this as duplicate of #3092

**Closed** 2021-05-23 08:27 UTC
