### ISSUE TITLE
Afaan Oromoo

### ISSUE THREAD

**Issue by teshomegit** [common-voice/common-voice#3685] opened 2022-04-30 16:34 UTC
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

**Language code**

**Language size**

**Plural forms**

**Pontoon manager**

**Language Script**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment] 2022-04-30 16:41
Closed as duplicate of #3685.

**Closed by ftyers** 2022-04-30 16:41 UTC
