### ISSUE TITLE
[BUG] Some texts in Profile page are not translatable

### ISSUE THREAD

**Issue by kwikwag** [common-voice/common-voice#4122] opened 2023-07-17 23:50 UTC
**Describe the bug**
Two titles in the Profile page don't go through translation: "Profile" and "Languages"

**To Reproduce**
1. Go to [the Spanish-version Profile page](https://commonvoice.mozilla.org/es/profile/info)
2. The titles are "Profile" and "Languages" rather than "Perfil" and "Idiomas" (for instance)

**Expected behavior**
The titles should match the translation language.

**Screenshots**
Note that the side bar says "Perfil" but the title is "Profile".
<img width="385" alt="image" src="https://github.com/common-voice/common-voice/assets/392199/ad2d53f2-ac8a-401a-8a75-0e0a9b3e7b7a">

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 114

**Comment by moz-rotimib** [comment] 2023-07-18 08:43
Thanks for reporting this.

The issue is that the text here is hardcoded with an English string instead of a pontoon key. We have a ticket to fix this, which will be resolved in the coming weeks.

**Comment by moz-rotimib** [comment] 2023-07-26 07:59
This issue has been fixed in this [PR](https://github.com/common-voice/common-voice/pull/4132) and will be released in the next release so I am closing this issue

**Closed by moz-rotimib** 2023-07-26 07:59 UTC
Labels: Bug
