### ISSUE TITLE
[iOS] none of the login options respond to taps

### ISSUE THREAD

**Issue by sfoster** [common-voice/common-voice#1937] opened 2019-04-09 21:36 UTC
Using iPad Pro with all iOS updates (12.1.4), with and without a bluetooth keyboard attached, the common voice app "Login/Sign up" screen has 

"voice.mozilla.org"
[Log in with email]
[Enter]
[Log in with Firefox]
[Log in with Github]
[Log in with Google]

...Tapping on *any* of these inputs or buttons has no visible effect. I don't get focus or a keyboard for the email field, and there's no response when tapping on the Log in buttons.

**Comment by sfoster** [comment] 2019-04-09 21:38
Possibly related, the Contact Form (again, from within the iOS app) allows me to fill the fields, but Submit appears to do nothing.

**Comment by rleitan** [comment] 2019-04-10 08:12
I cannot reproduce the issue on Common Voice app - iOS 12.1 (iPhone)

**Comment by hmitsch** [comment] 2019-04-10 09:08
@sfoster, can you still reproduce this issue?

@rleitan thanks for the super-quick feedback.

**Comment by StregaNona** [comment] 2019-04-16 02:41
Hi @hmitsch.  I’m Kelley Green, Sam’s wife.  He filed this on my behalf.  I’m on an iPad Pro and it still doesn’t work.  It’s both the login form *and* the help form, which makes it difficult for people to report it if their spouse doesn’t work for Mozilla. :)

**Comment by hmitsch** [comment] 2019-04-16 05:03
Hi @StregaNona, thanks for reaching out. I appreciate the effort you take to help us nail down this issue.

Do you have any screenshots which would help us understand your problem better? If you don't want to post them publicly in this thread, please email me at hmitsch@mozilla.com

Thanks for your support!
Best regards,
   Henrik

**Comment by StregaNona** [comment] 2019-04-16 14:47
![IMG_1057](https://user-images.githubusercontent.com/49666212/56219435-9b748900-601b-11e9-8339-682cb405b27f.png)

This login popup won’t allow me to type at all and the buttons don’t ‘push’ or react when I touch them.

![IMG_1058](https://user-images.githubusercontent.com/49666212/56219449-a16a6a00-601b-11e9-863b-001a141cd9b1.png)

The Contact form popup allows for input but still shows no response to trying to click the ‘send’ button.

**Comment by StregaNona** [comment] 2019-04-16 14:50
Also...I can log in just fine on the Safari site on iPad Pro...and the Contact form appears to work fine there.

**Comment by pslawless** [comment] 2019-06-05 20:27
I also see the same issue (login screen that won't let me type an email address or click any button).

**Comment by StregaNona** [comment] 2019-06-05 20:30
Unfortunately...the help form, while letting you fill in your info, won’t send either. :(

**Comment by MichaelKohler** [comment] 2020-02-22 01:43
Is this still an issue?

**Comment by StregaNona** [comment] 2020-02-22 02:52
I gave up when no one seemed to care.  I’ll go try it again.

And those who were seen dancing were thought to be insane by those who could not hear the music. - Friedrich Nietzsche

**Comment by StregaNona** [comment] 2020-02-22 02:52
Still doesn’t work

And those who were seen dancing were thought to be insane by those who could not hear the music. - Friedrich Nietzsche

**Comment by Rexogamer** [comment] 2020-02-22 19:15
Same thing on my iPad Air 3 running iOS 13.3.1. At least the website works fine enough in Chrome.

**Comment by phirework** [comment] 2021-02-05 23:31
Closing issue as the iOS app is no longer supported. I apologize for the frustration and lack of responsiveness you experienced!

**Closed by phirework** 2021-02-05 23:31 UTC
Labels: Type: Investigate
