### ISSUE TITLE
LOCALISATION REQUEST: Kalenjin [kln]

### ISSUE THREAD

**Issue by akebut** [common-voice/common-voice#4335] opened 2024-01-22 16:47 UTC
# Welcome to the Common Voice Community !

I am writting to request for  local language localization , Kalenjin is a nilotic  language spoken in the great riftvalley kenya. Any assistance on this matter will be highly apreciated

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

**Language code**

**Language size**

**Plural forms**

**Pontoon manager**

**Language Script**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment] 2024-01-22 16:51
Hi @akebut thanks for your interest in Common Voice! Could you help us by filling out the form above? If you need any help, please feel free to get in contact on our [Matrix channel](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by ftyers** [comment] 2024-01-29 15:37
This is a duplicate of #4347.

**Closed by ftyers** 2024-01-29 15:37 UTC
