### ISSUE TITLE
IsiXhosa

### ISSUE THREAD

**Issue by Lustarman** [common-voice/common-voice#3125] opened 2021-05-21 09:16 UTC
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
IsiXhosa

**Language code**
xh

**Language size**
20 million

**Plural forms**
How would you translate the following in this language?

0 rocks - amatye angekhoyo
1 rock - ilitye elinye
2 rocks - amatye amabini
3 rocks - amatye amathathu
4 rocks - amatye amane
5 rocks - amatye amahlanu
10 rocks - amatye alishumi
20 rocks - amatye angamashumi amabini
100 rocks - amatye alikhulu
1000 rocks - amatye aliwaka
I see 0 rocks on the ground - Ndibona amatye angekhoyo emhlabeni
I see 1 rock on the ground - Ndibona ilitye elinye emhlabeni
I see 10 rocks on the ground - Ndibona amatye alishumi emhlabeni
I see rocks on the ground - Ndibona amatye emhabeni

**Pontoon manager**
https://github.com/Lustarman

**Comment by ftyers** [comment] 2021-05-21 16:35
This is a duplicate of #3030.

**Comment by Heyhillary** [comment] 2021-08-18 09:48
Hey @Lustarman,

I'm messaging to follow up with your request. As the respondent, who originally requested isiXhosa  #3030  hasn't responded. Would it be possible if you could send to me your pontoon account name, please ?

Pontoon works separately from github. You can create an account here: https://pontoon.mozilla.org

**Comment by ftyers** [comment] 2022-10-24 19:53
isiXhosa is now enabled and translated. https://pontoon.mozilla.org/xh/common-voice/

**Closed by ftyers** 2022-10-24 19:53 UTC
Labels: Localization
