### ISSUE TITLE
Language codes: ISO 639-1 vs. regional codes

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#2550] opened 2020-01-31 12:06 UTC
Currently we are using the 639-1 (two letters) code for most languages. However there are the following codes that use the language-region format:

* fy-NL
* ga-IE
* hi-IN (see https://github.com/Common-Voice/sentence-collector/pull/295)
* nb-NO
* nn-NO
* ne-NP
* pa-IN
* rm-sursilv
* rm-vallader
* sv-SE
* zh-CN
* zh-HK
* zh-TW

These are the ones I know about. There might be more available in Pontoon. Some of these might actually be different enough to warrant a more specific code, but on the suggestion of @nukeador  I'm filing this issue to figure out which ones need to be so specific and which ones do not.

**Comment by MichaelKohler** [comment] 2020-01-31 12:11
Common Voice currently takes the code from Pontoon, and there is no mapping. The locale for "pt-BR" and "pt-PT" have been consolidated a few months back, and now it's just "pt" on Pontoon. In the end according to Nuke we only want two-letter codes in the data set where possible.

**Comment by ftyers** [comment] 2020-01-31 12:27
Some of the locales might be shorthand for script, e.g. `pa-IN` is probably in [Gurmukhi not Shahmuki](https://en.wikipedia.org/wiki/Punjabi_language#Writing_systems).

Some comments on the others:

* fy-NL: probably not necessary
* ga-IE: probably not necessary, the only locale related thing would be currency I guess.
* nb-NO, nn-NO: not necessary, but this is a really weird situation
* ne-NP: probably not necessary
* pa-IN: probably necessary, unless replaced by pa-Guru, pa-Arab
* rm-sursilv, rm-vallader: probably necessary
* sv-SE: probably not necessary
* zh-CN, zh-TW, zh-HK: not sure, but could this be related to simplified/traditional?

**Comment by nukeador** [comment] 2020-02-03 12:09
@peiying2 can you please check this? Let me know how we can sync to make sure we align on this one and move it forward. Thanks!

**Comment by MichaelKohler** [comment] 2020-02-29 00:19
@peiying2 any update on this?

**Comment by MichaelKohler** [comment] 2020-03-21 13:54
@peiying2 ping again

**Comment by peiying2** [comment] 2020-03-22 02:48
@MichaelKohler apologize for letting this fall through the crack.  For the removal of the country code or consolidate of two to one, I have to check with the communities. 
Like `pt`, we don't have communities identify themselves with that and usually associate themselves with a country code, I need to get their buy-ins.

> Some of the locales might be shorthand for script, e.g. `pa-IN` is probably in [Gurmukhi not Shahmuki](https://en.wikipedia.org/wiki/Punjabi_language#Writing_systems).
> 
> Some comments on the others:
> 
>     * fy-NL: probably not necessary
We can consider this.  Let me check with the contributor.

>     * ga-IE: probably not necessary, the only locale related thing would be currency I guess.
Apparently there is also Scottish Gaelic: https://en.wikipedia.org/wiki/Goidelic_languages check the table in the lower part of the page and see the examples. I am not sure how intelligible one is to the other. 
>     * nb-NO, nn-NO: not necessary, but this is a really weird situation
These two are required in Norway as official languages.

>     * ne-NP: probably not necessary
The assumption is that Nepal is the predominant country to use the language. 

>     * pa-IN: probably necessary, unless replaced by pa-Guru, pa-Arab
There are two written versions for Punjabi. However, Punjabi in Pakistan is written in Arabic script.  We do not have a community for Punjabi in Arabic, at least not so far. 
- pa-Guru: https://github.com/unicode-cldr/cldr-localenames-modern/tree/master/main/**pa-Guru**
- I can't find the CLDR convention for Punjabi in Arabic.
Note: If we change the locale code, it will be for Common Voice only. We have to talk to the community to see if they want to move to this new locale for other projects.

>     * rm-sursilv, rm-vallader: probably necessary
Correct, the person requested specifically called out the difference on these, and it was from the same person for both locales.
> 
>     * sv-SE: probably not necessary
Yes, most likely.

>     * zh-CN, zh-TW, zh-HK: not sure, but could this be related to simplified/traditional?
Yes, let's remove `zh-HK`. zh-HK is written in zh-TW as far a s coding goes, but the spoken part is different - Cantonese, which is not what we are discussing here. Even if the expression is more Hong Kong oriented, they can contribute to the pool of strings for zh-TW.

**Comment by nukeador** [comment] 2020-03-23 11:31
Please note pt was already changed in the past as a single two-letter code. This is the standard list Common Voice is following and applying on our datasets:

https://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html

Since the site and the sentences are script-dependent, we need to take this in consideration

https://www.unicode.org/cldr/charts/latest/supplemental/languages_and_scripts.html

From our languages and accents strategy:

> We realize that the way that Mozilla has historically identified languages/locales with variants might not always be useful for Common Voice and Deep Speech goals.
> 
> For this project needs, we consider a dataset-language a common writing system that contains the same words, grammar and script, acknowledging that non-formal expressions can happen in different territories.
> 
> Example: Spanish in Spain and Spanish in Mexico should be both considered “Spanish” at a dataset-language level.
>

**Comment by peiying2** [comment] 2020-04-02 21:57
@nukeador yes, I have used the same guidelines when discussing the issues with the community.
@MichaelKohler here is the summary:
1) Yes
- `fy-NL` -> `fy` 
- `ga-IE` -> `ga`
- `ne-NP` -> `ne`
- `pa-IN` -> 'pa' (NOTE, if the language is written in Arabic, the locale code is `pnb`. So far, we don't have contributors requesting a different script. `pa` usually refers to the Gurmukhi script. This has been the case with Wikipedia use cases).
- `sv-SE` -> `sv`

2) No
- `nb-NO` and `nn-NO`: these two are separate languages, like the Indic languages in India. Also the government requires both languages co-exist.
- `rm-sursilv`, `rm-vallader`: there is no country code in either language code. The community is ok with using `rm` for legal documents.
-  `zh-CN`, `zh-TW`, `zh-HK`: For UI zh-TW and zh-HK can be combined, but the site lacks dialect breakdown in dropdown menu for the dialiact, and the characters (corpus) from zh-HK can't be merged to either zh-CN or zh-TW because many are unique to conversational expressions (in characters).

**Comment by peiying2** [comment] 2020-04-02 21:59
Once we decide this is a good interim solution, we should coordinate with dev and Pontoon to make it happen. I have to add new locales in Pontoon, and then the data migration to preserve contributor information in Pontoon.

**Comment by MichaelKohler** [comment] 2020-04-03 12:11
Thanks for the feedback. I'd be happy to help with the mapping from the Sentence Collector down the road.

What about hi-IN? Might be answered with `like the Indic languages in India`, but I'm not sure. If we want to keep that, we'll need to merge https://github.com/Common-Voice/sentence-collector/pull/295.

**Comment by peiying2** [comment] 2020-04-10 16:48
> What about hi-IN? Might be answered with `like the Indic languages in India`, but I'm not sure. If we want to keep that, we'll need to merge [Common-Voice/sentence-collector#295](https://github.com/Common-Voice/sentence-collector/pull/295).
Confirmed with Hindi community and they agree to have it displayed as `hi`. I have updated the list above so you have one place to check the latest I gathered from the communities.

**Comment by nissa1992** [comment] 2020-08-17 23:31
anybodi help can i join for my language

**Comment by peiying2** [comment] 2020-08-19 00:33
> anybodi help can i join for my language

Please check to see if your language is already listed here: https://pontoon.mozilla.org/projects/common-voice/. If not, you can make a request in Pontoon. v

**Comment by Heyhillary** [comment] 2022-01-13 16:26
Hey @MichaelKohler,

I'm currently going through github issues for triaging and came across your request. 

With the [new change ](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/) brought by the languages, variants and accents work. BCP-47 will allows communities to pull out key information such as region, dialect and orthography.

Are you happy with me closing the issue ?

**Closed** 2022-01-13 16:38 UTC
Labels: Type: Enhancement, Type: localization
