### ISSUE TITLE
LOCALISATION REQUEST: Ladin (Gherdëina)

### ISSUE THREAD

**Issue by schtailmuel** [common-voice/common-voice#4726] opened 2024-12-19 10:58 UTC
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

Ladin (Gherdëina)

**Language code**

- ISO 639-3: lld
- IETF BCP 47 language tag: lld_gherd

**Language size**

~10.000

**Plural forms**

nul sasc
un n sas
doi sasc
trëi sasc
cater sasc
cin sasc
diesc sasc
vint sasc
cënt sasc
mile sasc
I ne vëije degun sas sun fonz
I vëije un n sas sun fonz
I vëije diesc sasc sun fonz
I vëije sasc sun fonz

**Pontoon manager**

[Samuel Frontull](https://pontoon.mozilla.org/contributors/JND7woaT8Gzx_FVxHGMum_x25pU/)

**Language Script**

Latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [X] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
Our goal is to make the Ladin language accessible in digital spaces, especially in the context of language technologies. By participating in Common Voice, we can help create a high-quality, freely available dataset of Ladin language that will enable the development of speech recognition systems and other AI applications for this underrepresented language.

In addition, it is important to us to respect and preserve the linguistic diversity of Ladin itself. By registering variant tags, we ensure that each unique dialect and regional variant is adequately represented. 

2. [optional to share] Would you like to have a follow-up conversation regarding community building ?
Yes, I would greatly appreciate a follow-up conversation regarding community building.

**Comment by ftyers** [comment] 2024-12-19 22:40
Duplicate of #4725, we we deal with the different variants from inside the same language code.

**Closed by ftyers** 2024-12-19 22:40 UTC
Labels: Localisation
