### ISSUE TITLE
[BUG] Registering with email goes to 404

### ISSUE THREAD

**Issue by Huguet57** [common-voice/common-voice#3724] opened 2022-06-01 10:00 UTC
**Describe the bug**
When registering to the site with e-mail, you receive a mail with a registration link that sends you to 404. Registering with Google works well. 

**To Reproduce**
1. Go to [https://commonvoice.mozilla.org/login](https://commonvoice.mozilla.org/login)
2. Introduce your email
3. Click send email
4. Click the registration link sent to email
5. End up in 404

**Expected behavior**
You should register a new account.

**Screenshots**
![404 page](https://user-images.githubusercontent.com/6130834/171379121-742f4c11-e7e2-4e45-92f7-82802c53308e.jpeg)

**Desktop or Mobile (please complete the following information):**
 - Desktop (Google Chrome) and mobile (Android)

**Additional context**
The catalan page, haven't tried others.

**Comment by mozgzh** [comment] 2022-06-07 12:36
Thanks for filling the issue! I've confirmed it is still occurring and have created a ticket to get it fixed.

**Comment by fycdev** [comment] 2022-08-04 15:33
Hi @mozgzh I reproduced the bug and went to investigate.

I looked into the network tab to see what is causing the 404 and it is coming from routing in react. From my understanding, the link provided in the email takes you to an authentication endpoint which then redirects you to `commonvoice.mozilla.org/callback?code=...&state=...`, which then redirects you to `commonvoice.mozilla.org/login-success`. 

I have a strong suspicion that the final redirect `/login-sucess` is missing the locale path and its causing the router to spit out a 404. Perhaps the issue lies in `server/src/auth-router.ts` which handles the redirecting.

**Comment by fycdev** [comment] 2022-08-04 15:46
I looked into `auth-router.ts`, the encrypted string value for the query param `state` in that `/callback` url probably does not include the `locale` property when it gets decrypted and `JSON.parse`'d. Thus the router constructs the redirect route as just `/login-success`.

**Comment by fycdev** [comment] 2022-08-05 05:30
I believe I have found the cause of this issue.

The `/login` redirect relies on the `Referer` header to get the locale so it can encrypt it into the `state` query param.
If the `/login` was navigated via user interaction (e.g clicking the login button etc) the referrer url will include the locale path at the end, and thus the locale would be included in the encrypted string and user flow will work correctly.

However, if the user navigates directly via the address bar, or from cross origin then there is no locale path to encrypt and the callback URLs will be incorrectly constructed. Eventually, leading to the 404 error.

I have tested this in Firefox, Chrome and Safari and all yielded the same results.

My suggestion is to add a default locale before the `state` value gets encrypted at `auth-router.js:196`. I am not strictly a backend dev so not sure if this is the right way to approach it.

What are your thoughts @mozgzh @Heyhillary ?

**Closed** 2024-02-26 11:30 UTC
Labels: Bug
