### ISSUE TITLE
The avatar picture can't be changed 

### ISSUE THREAD

**Issue by ovidiuboca1** [common-voice/common-voice#2405] opened 2019-11-21 13:12 UTC
Tested with Windows 10, Mac OS X 10.14 and Ubuntu 16.04 on Firefox 70, Safari 13.0.3 

Prerequisites: 
You need to have an account for Common Voice

STR:
1.  Open https://voice.mozilla.org/en and login  
2. Go to Profile 
3. Select Avatar
4. Upload an image. 

Actual results:
There are 2 results, in this case, it depends on what kind of account you have.

1. If you have an account that already has an avatar picture the actual result is that after step 4 nothing happens, your avatar picture is not uploaded, is not changed and there is no error message. 

2.  If you have an account that doesn't have an avatar picture the actual result is that after step 4 you receive a message error saying that the picture is too large. I tested with a picture that has 131 KB and I have the same error.  Here is a screen recording: https://streamable.com/2n871

Actual Results: You can change the avatar picture without any errors. 

NOTE: Only with Chrome on Windows 10 we manage to change the avatar picture without any errors.

**Comment by rileyjshaw** [comment] 2019-11-21 22:13
@phirework could this be related to https://github.com/mozilla/voice-web/commit/f6c3b2c44b373807f2383efda26e422e4ba3638e?

**Comment by phirework** [comment] 2019-11-21 22:24
So I don't think so, because @mbransn first reproduced this bug on Prod in #2388 before f6c3b2c was deployed to Prod: 

https://github.com/mozilla/voice-web/issues/2388#issuecomment-556503395

Also, I couldn't see anything in the source of `resizeImage` that indicated that a different number would break the entire funciton.

**Comment by aryamanpuri** [comment] 2020-02-24 16:04
What is the size limit for the avatar ?

**Comment by mbransn** [comment] 2020-02-24 22:03
@aryamanpuri 200px max width if I remember correctly based on comments in #2388 -- unsure what the actual file data size limit is or if there is one. cc @rileyjshaw @phirework to help clarify.

**Comment by shakti97** [comment] 2020-03-28 20:00
I would like to work on this issue

**Comment by shakti97** [comment] 2020-03-29 17:50
I investigate this issue and found that the frontend is working fine :- in resizing the image to come under width:200 and height: 200 but
Root Cause:- avatarUrl length goes above 8000, and in the backend we are constraining it to below 8000. 
am I on the right path @rileyjshaw @phirework

**Comment by cloudrac3r** [comment] 2020-07-12 12:26
I experimented by converting the same file with imagemagick at various dimensions and qualities, checking the size with wc -c, and then trying to upload it, and noting the results. Here's what I found:

|Works|Dimensions|Quality|File size|
|:--|:-:|:-:|:-:|
|:heavy_check_mark: Yes|110x110|50|2154 bytes|
|:x: No|110x110|60|2368 bytes|
|:x: No|110x110|88|4173 bytes|
|:x: No|110x110|90|6108 bytes|
|:heavy_check_mark: Yes|96x96|90|4915 bytes|

Conclusions:

- The problem is not exclusively with number of bytes, since 2368 (small) was rejected and 4915 (large) was accepted.
- The problem is not exclusively with file quality, since a q60 (small) was rejected and a q90 (large) was accepted.
- The problem is not exclusively with dimensions, since some 110x110 were rejected and some 110x110 were accepted.

So I have no idea how it decides if the file is too large or not.

It's not random - trying to upload the same file again produces the same result as the other times I tried to upload the file.

**Comment by phirework** [comment] 2020-07-13 18:39
This is awesome, thanks for the extensive troubleshooting @cloudrac3r! The source of the problem is known (relates to base64 encoding length) and we're working on a fix for this. cc @NanaKay007

**Comment by phirework** [comment] 2021-04-21 22:02
This is finally, finally fixed 😁

**Closed by phirework** 2021-04-21 22:02 UTC
Labels: Type: Bug
