### ISSUE TITLE
Recorded sentences are not played back in full

### ISSUE THREAD

**Issue by deevroman** [common-voice/common-voice#3048] opened 2021-03-22 13:01 UTC
**Describe the bug**
Recorded sentences are not played back in full

**To Reproduce**
1. Record the sentence
2. Try to play it back
3. Only the first few seconds are played

 - OS: macOS
 - Browser Firefox
 - Version 87

**Comment by guojimhuang** [comment] 2021-03-26 12:21
Same bug here on
OS: ubuntu 20.10
Browser Firefox
Version 87.0

**Comment by phirework** [comment] 2021-03-26 20:39
This appears to be a duplicate of #3018, closing this one and will do additional troubleshooting in that earlier issue.

**Comment by phirework** [comment] 2021-03-29 21:19
Nvm - after troubleshooting it looks like the issue might be isolated to FF 87 specifically, will re-open and update as I find out more.

**Comment by zitr0y** [comment] 2021-03-29 21:34
Same issue here.
OS: Windows 10 Pro 20H2
Browser: Firefox 87.0 (64-Bit) 
Language: German and English recording (haven't tried others)
Microphone: AT 2020+ USB

**Comment by nikolockenvitz** [comment] 2021-03-30 05:43
Same here.
OS: Windows 10
Browser: Firefox 87.0 (64-bit)

**Comment by zitr0y** [comment] 2021-03-30 15:41
The dev server version works perfectly for me 👍

**Comment by stefangrotz** [comment] 2021-03-30 15:44
Works fine for me as well 👍

**Comment by deevroman** [comment] 2021-03-30 16:10
It works for me too 👍

**Comment by nikolockenvitz** [comment] 2021-03-30 16:41
Yes, works perfectly fine! Thanks

**Comment by phirework** [comment] 2021-03-30 23:06
The hotfix is out on production, thanks everyone!

**Closed by phirework** 2021-03-30 23:06 UTC
Labels: Priority: urgent, Status: claimed
