### ISSUE TITLE
[BUG] Sentences are not accepted on the new sentence collector app for Amharic

### ISSUE THREAD

**Issue by quaja-abu** [common-voice/common-voice#4044] opened 2023-05-14 18:43 UTC
**Describe the bug**
The new release sentence collector is not accepting valid sentences for Amharic.

**Expected behavior**
Accept valid sentences according to the rule created for the language.

**Screenshots**

![bug](https://github.com/common-voice/common-voice/assets/58632941/dc4f1634-1627-4858-90a8-3906db2557c5)
The screenshot shows that I inserted a valid sentence and it gives me a red toast that says "ዓረፍተ-ነገር ማከል ላይ ስህተት ተፈጥሯል" which means "There was an error adding a sentence".

**Comment by moz-rotimib** [comment] 2023-05-15 08:54
Hello, @quaja-abu thanks for flagging this issue.

Please could you send the text you tried to contribute so I can try to reproduce this issue myself? I've tried copying the text from the image but sadly I cannot.

Best regards,

Rotimi

**Comment by quaja-abu** [comment] 2023-05-15 14:04
The sentence is:
ሴኮባ ኮናቴ ጊኒ ውስጥ የሚገኝ ጁንታ ጊዜያዊ መሪ በመታመሙ ወደ ሴኔጋል ተወሰደ

Which is found here line 7:-

https://github.com/asmelashteka/HornMT/blob/main/data/amh.txt

በሰኞ፣ ሜይ 15 2023 11:54 AM moz-rotimib ***@***.***> ላይ የሚከተለው
ተጽፏል፦

**Comment by moz-rotimib** [comment] 2023-05-15 14:21
Thanks for the response @quaja-abu I've tried to add the sentence myself and I get the error as you do. 

I checked the network request and it seems the reason the sentence is rejected is because it contains abbreviations (check screenshot)

<img width="313" alt="Screenshot 2023-05-15 at 16 18 08" src="https://github.com/common-voice/common-voice/assets/113194143/29a8f326-ec1b-4ad5-be16-6bb3f61536b0">

As an improvement to the write page, we will make the error messages clearer to users so they know what the exact validation error is. Let me know if you have any further questions.

I hope this helps.

Rotimi

**Comment by quaja-abu** [comment] 2023-05-15 16:06
OK I see but there is no abbreviation in the sentence and I tried it with
another sentence and it still didn't accept it. See the attachment.

በሰኞ፣ ሜይ 15 2023 5:22 PM moz-rotimib ***@***.***> ላይ የሚከተለው
ተጽፏል፦

**Comment by quaja-abu** [comment] 2023-05-15 16:33
![Screenshot_20230515_190253_Firefox](https://github.com/common-voice/common-voice/assets/58632941/90caf5db-e6ec-483d-813d-941009746a52)
Here is the screenshot

**Comment by moz-rotimib** [comment] 2023-05-15 16:39
I get the same error too and it is rejected because of the no abbreviations rule.

I think the abbreviation validation rule we use for Amharic needs to be updated so unfortunately some sentences might not be able to be contributed till this is fixed.

**Comment by quaja-abu** [comment] 2023-05-15 16:47
You are right. I will try to work on that myself. I was the one that I created the rule. FYI the regex is supposed to identify Amharic words that are separated by .(dot)

**Comment by quaja-abu** [comment] 2023-05-15 16:50
But abbreviations might also separated by back slash (/) in too Amharic. Forexample, ዓ.ም or ዓ/ም , እ.ኤ.አ, ዶ.ር etc. We should consider backslash too for the update I guess!

**Comment by quaja-abu** [comment] 2023-05-15 16:52
By the way in the previous sentence collector it was working fine. I don't know why it is not working right now.

**Comment by moz-dfeller** [comment] 2023-05-16 10:32
Fixed in #4050

**Closed by moz-dfeller** 2023-05-16 10:32 UTC
Labels: Bug
